<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:output method="html" indent="yes" encoding="utf-8" omit-xml-declaration="yes" doctype-public="XSLT-compat"/>
<xsl:strip-space elements="*"/>

<xsl:include href="index.xsl"/>
<xsl:include href="snippets/subnav_help.xsl"/>

<xsl:template match="/">
	<xsl:choose>
		<xsl:when test="root/meta/ajax != ''">
			<xsl:apply-templates select="/root/content"/>
		</xsl:when>
		<xsl:otherwise>
			<xsl:apply-templates select="root"/>
		</xsl:otherwise>
	</xsl:choose>
</xsl:template>

<xsl:template match="content">
	<div class="content">
		<xsl:call-template name="subnav_help" />
		<div class="clearer"></div>
		<div class="threeColumn">
			<div class="padding15All">
				<div class="largeSectionWhite">
					<h3>Privacy Policy</h3>
					<div style="white-space: pre-wrap;">
						<p>This Privacy Policy applies to Web sites owned and operated by Life Care Planning Solutions, LLC, including Medvoyager.com including the mobile optimized version of this site. This Privacy Policy also applies to the Medvoyager Mobile Device Application (or "App") for the iPhone, the iPad and mobile devices operating with the Android operating system. Except where noted, statements in this Privacy Policy with respect to our Web sites also apply to our Medvoyager Mobile Device App.</p>
						<p>Reference to "Medvoyager" means Life Care Planning Solutions, LLC, including any company that Life Care Planning Solutions, LLC. controls (for example, a subsidiary that Life Care Planning Solutions, LLC. owns). “Life Care Planning Solutions sites" include any site that Life Care Planning Solutions owns or controls. Life Care Planning Solutions may share information among its subsidiaries or sites that it owns or controls, but is always protected under the terms of this Privacy Policy.</p>
						<p>The Medvoyager site contains links to other sites. Once you enter another Web site (whether through an advertisement, service, or content link), be aware that Life Care Planning Solutions is not responsible for the privacy practices of these other sites. We encourage you to look for and review the privacy statements of each and every Web site that you visit through a link or advertisement on Medvoyager.</p>
						<p>We hope that reading our Privacy Policy helps you understand how we manage information about you. While you may use some of the functionality of Medvoyager without registration, many of the specific tools and services on our website require registration. If you use our Web site without registering, the only information we collect will be Non-Personal Information through the use of Cookies or Web Beacons. If you choose to register with our Web site for certain Interactive Tools or other services, we require you to submit Personally Identifiable Information. Depending on the tool or service you have selected, we may also collect Personal Health Information. You are responsible for ensuring the accuracy of the Personally Identifiable Information and Personal Health Information you submit to Medvoyager. Inaccurate information will affect the information and services you receive when using our site and tools and our ability to contact you as described in this Privacy Policy. For example, your email address should be kept current because that it is how we communicate with you.</p>
						<h5>Non-Personal Information We Collect About You</h5><br />
						<p>Even if you do not register with Medvoyager, we collect Non-Personal Information about your use of our Web site, special promotions and newsletters.</p>
						<br />
						<h5>Cookies</h5>
						<p>We collect Non-Personal Information about your use of our Web site and your use of the Web sites of selected sponsors and advertisers through the use of Cookies. Every computer that accesses a Medvoyager Web site is assigned a different Cookie by Medvoyager. The information collected by Cookies (i) helps us dynamically generate advertising and content on Web pages or in newsletters, (ii) allows us to statistically monitor how many people are using our Web site and selected sponsors' and advertisers' sites, (iii) how many people open our emails, and (iv) for what purposes these actions are being taken. We may use Cookie information to deliver certain advertisements to your browser on our owned or operated Web sites based on areas of the Site that you have visited during the same session or to determine the popularity of certain content or advertisements. In connection with our sale of advertising we may allow third parties to place a cookie on your browser in order to enable advertisers to recognize your browser in order to deliver an advertisement based on non-personally identifiable information. Importantly, we do not allow these advertisers to collect any information based on your visits to Medvoyager. We may also acquire Non-Personal Information about our users that these third parties have access to and we may use that information for the purpose of content development and for marketing purposes. Cookies are also used to facilitate a user's log-in, as navigation aids and as session timers. Cookies used by Medvoyager are also used to restrict underage use of the tools. We also use cookies in order to enable us to conduct surveys for our own use and on behalf of our advertisers. These cookies are used to determine whether you have seen certain content or advertising so that we may request your opinions.</p>
						<p>Most browser software can be set to reject all Cookies. Most browsers offer instructions on how to reset the browser to reject Cookies in the "Help" section of the toolbar. If you reject our Cookies, certain of the functions and conveniences of our Web site may not work properly but you do not have to accept our Cookies in order to productively use our site. Additionally Medvoyager may geographically target advertising based on your IP address. We use local shared objects, also known as Flash cookies, to enable you to use certain interactive tools on our site. Flash cookies are different from browser cookies because of the amount and type of data they collect, and how the data is stored. </p>
						<p>Cookie management tools provided by your browser will not remove Flash cookies. To learn how to manage privacy and storage settings for Flash cookies, please visit the Macromedia Site.</p>
						<h5>Mobile Device Applications (Apps)</h5>
						<p>When you download and install our Medvoyager Mobile App onto your mobile device we assign a random number to your App installation. This number cannot be used to identify you personally, and we cannot identify you personally unless you choose to become a registered user of the App. We use this random number in a manner similar to our use of Cookies as described in this Privacy Policy. Unlike Cookies the random number is assigned to your installation of the App itself and not a browser, because the App does not work through your browser. Therefore the random number cannot be removed through settings. If you do not want us to use the random number for the purposes for which we use Cookies, please do not use the Mobile Device App and please use your mobile device browser to access our Web sites or our mobile optimized sites. We do not obtain any information about your mobile device, other than the brand, make and model and type of operating software your device uses.</p>
						<h5>Physical Location</h5><br />
						<p>Medvoyager obtains your consent (via an opt-in) before using information from pin-pointing technology like GPS or cell tower information. You can withdraw your consent (opt-out) for the use of "location" by Medvoyager at any time by changing your location services in the "Settings" function on your mobile device.</p>
						<br />
						<h5>Web Beacons</h5>
						<p>We also may use Web Beacons to collect Non-Personal Information about your use of our Web site and the Web sites of selected sponsors and advertisers, and your use of special promotions or newsletters. The information collected by Web Beacons (i) allows us to statistically monitor how many people are using our website and selected sponsors' and advertisers' sites, (ii) how many people open our emails, and (iii) for what purposes these actions are being taken. Also we may use web beacons and Cookies to deliver advertisements on any of the Web sites owned or operated by Medvoyager based on areas of our Web sites that you have visited during the same session.</p>
						<br />
						<h5>Third Parties Collecting Non-Personal Information on Medvoyager's Behalf</h5>
						<p>Third parties with Medvoyager may use Cookies or Web Beacons to collect Non-Personal Information about your usage of Medvoyager’s sites. These third parties may use this information, on our behalf, to help Medvoyager deliver our advertising on other sites on the Internet based on your browsing activity on our sites. Medvoyager may further tailor the advertising on these third party sites based on other Non-Personal Information such as your geographic location (zip code), gender and/or age range to the extent known by these third parties. These third parties have agreed not to use Non-Personal Information they collect from our sites except to deliver advertisements on our behalf. If your browser is set to reject cookies, the Non-Personal Information will not be sent to these third parties and will not be used to deliver ads on third party sites. </p>
						<br />
						<h5>Personally Identifiable Information We Collect About You</h5><br />
						<p>We collect Personally Identifiable Information, like your name, email address, date of birth, and zip code, you provide to us when you register as a member of Medvoyager and/or when you update your member profile. We use the Personally Identifiable Information that you provide to respond to your questions, provide you the specific services you select, send you emails about Web site maintenance and updates, and inform you of significant changes to this Privacy Policy.</p>
						<h5>Emails You Send to Medvoyager</h5>
						<p>This Privacy Policy does not apply to content, business information, ideas, concepts or inventions that you send to by email. If you want to keep content or business information, ideas, concepts or inventions private or proprietary, do not send them in an email to Medvoyager. We try to answer every email within 48 business hours, but are not always able to do so.</p>
						<br />
						<h5>Website Registration and Interactive Tools on Medvoyager</h5>
						<p>After you have registered as a member of Medvoyager, you may choose to use certain Medvoyager interactive content, tools and services that may ask you to voluntarily provide other types of information about yourself including Personal Health Information. Some of the tools store your Personal Health Information in accordance with the authorization you provide at the time you use the tool.</p>
						<h5>Children</h5>
						<p>We are committed to protecting the privacy of children. Neither Medvoyager nor any of its services are designed or intended to attract children under the age of 13. We do not collect Personally Identifiable Information from any person we actually know is under the age of 13. A parent or guardian, however, may use Medvoyager to establish a personal health record and emergency contact list for a minor. The parent or guardian is solely responsible for providing supervision of the minor's use of Medvoyager. The parent or guardian assumes full responsibility for ensuring that the registration information is kept secure and that the information submitted is accurate. The parent or guardian also assumes full responsibility for the interpretation and use of any information or suggestions provided through Medvoyager for the minor.</p>
						<h5>Aggregate Data</h5>
						<p>Medvoyager may combine, in a non-identifiable format, the Personal Health Information you provide with information from other users to create Aggregate Data that may be disclosed to third parties. Aggregate data does not contain any information that could be used to contact or identify you. For example, Medvoyager may use information gathered to create a composite profile of all the users of a particular third party site. These third party Web sites may use this information to understand community needs and to design appropriate programs and activities on their site. Medvoyager will not disclose your Personal Health Information to any third party without your prior permission, except as otherwise permitted by this Privacy Policy.</p>
						<h5>Information Collected by Third Parties Not Acting on Medvoyagers Behalf</h5><br />
						<p>Sponsors or advertisers on Medvoyager may use their own Cookies, Web Beacons or other online tracking technologies in the banner advertisements served on Medvoyager and in emails, special promotions or newsletters we send you. Some advertisers use companies other than Medvoyager to serve their ads and to monitor users' responses to ads, and these companies ("Ad Servers") may also collect Non-Personal Information through the use of Cookies or Web Beacons on our Web site. In certain situations, information collection may be facilitated by momentarily directing your browser to the Web site of an Ad Server or other third party acting on behalf of the sponsor, partner, or advertiser before re-directing your browser to its selected destination (e.g., back to Medvoyager to show the ad, or to the advertiser's website); this re-direction process will not be apparent to you.</p>
						<p>We do not control these third parties' use of cookies or Web Beacons, or how they manage the non-personal information they gather through them. However, we do require sponsors, advertisers and Ad Servers who collect cookie or web beacon information through our Web site to agree that they will not collect any Personally Identifiable Information from our site without your consent. They have promised us they will not link any non-personal cookie or web beacon information collected by them on our site to Personally Identifiable Information they or others collect in other ways or from other sites except as may be described in connection with a particular program. For example, in connection with "Ad links" furnished by Yahoo, non-personal information sent by your browser to Yahoo when you click on a sponsored link or submit a query may be used by Yahoo as described in its privacy policy. You should review the privacy policy of other sites you visit or link to from our site to understand how these other sites use cookies and how they use the information they collect through the use of cookies or web beacons on their own sites. Certain Ad Servers allow you to prevent them from collecting data through the use of cookies. In order to do so, you must Opt-out of such data collection with each individual site. Currently, you can Opt-out of Cookies for several Ad Servers by visiting the Privacy <a href="/opt-out">Network Advertising Initiative</a> gateway Opt-out site. This website will also allow you to review the Ad Server's privacy policies. You can find additional information and resources about how to opt out of advertising and related cookies by visiting the World Privacy Forum's Site.</p>
						<p>Medvoyager does not knowingly engage in business with any company that uses Spyware or Malware. We do not provide users with downloadable software that collects or uses any PII or PHI without full disclosure and Opt-in consent.</p>
						<h5>Disclosure of Your Information</h5><br />
						<p>Except as described in this Privacy Policy or as specifically agreed to by you, Medvoyager will not disclose any Personally Identifiable or Personal Health Information it gathers from you on our website. We may only release Personally Identifiable or Personal Health Information to third parties: (1) to comply with valid legal requirements such as a law, regulation, search warrant, subpoena or court order; or (2) in special cases, such as in response to a physical threat to you or others, to protect property or defend or assert legal rights. In the event that we are legally compelled to disclose your Personally Identifiable or Personal Health Information to a third party, we will attempt to notify you unless doing so would violate the law or court order. In addition, we may disclose Personal Information as described below.</p>
						<h5>Disclosure to Medvoyagers Operations and Maintenance Contractors</h5>
						<p>Medvoyager operations and maintenance contractors sometimes have limited access to your Personally Identifiable Information in the course of providing products or services to Medvoyager. These contractors include vendors and suppliers that provide us with technology, services, and/or content for the operation and maintenance of our Web site. Unless you have Opted-out of receiving emails and newsletters from Medvoyager, these contractors also may have access to your email address to send newsletters or special promotions to you on our behalf or to send emails to you for purposes such as conducting market research on our behalf. Access to your Personally Identifiable Information by these contractors is limited to the information reasonably necessary for the contractor to perform its limited function for Medvoyager. We also contractually require that our operations and maintenance contractors 1) protect the privacy of your Personally Identifiable Information consistent with this Privacy Policy, and 2) not use or disclose your Personally Identifiable Information for any purpose other than providing us with products and services as required by law.</p>
						<h5>Disclosure to Third Party Contractor Websites</h5>
						<p>Certain content and services offered to you through our website are served on Web sites hosted and operated by a company other than Medvoyager ("Third Party Contractor Web sites"). Medvoyager does not disclose your Personally Identifiable Information to these Third Party Contractor Web sites without your consent, but you should be aware that any information you disclose once you access these other Web sites is not subject to this Privacy Policy. Medvoyager does not endorse and is not responsible for the privacy practices of these Third Party Contractor Web sites. You should review the privacy policy posted on the other Web site to understand how that Third Party Contractor Website collects and uses your Personally Identifiable Information. Medvoyager makes an effort to make it obvious to you when you leave our website and enter a Third Party Contractor Web site, either by requiring you to click on a link or by notifying you on the site before you visit the third party site. In addition, if you see a phrase such as "Powered by" or "in association with" followed by the name of a company other than Medvoyager, then you are on a Web site hosted by a company other than Medvoyager.</p>
						<p>Medvoyager also provides links to sites provided by Third Party Contractor Websites that have business arrangements with Medvoyager to pay commissions based on sales of products or services generated through Medvoyager. </p>
						<h5>Disclosure to Linked Sites</h5>
						<p>In addition to the Third Party Contractor Web sites that you may access as described above, for your convenience there are links to Third Party Web sites operated by companies that are not affiliated with the Medvoyager Web site and that do not have contracts to provide content or services through the Medvoyager Web site. These links may be found in advertisements, referenced within content, or placed beside the names or logos of sponsors. Medvoyager does not disclose your Personal Information to these Third Party Websites without obtaining your consent. Medvoyager does not endorse and is not responsible for the privacy practices of these sites. If you choose to link to one of these Third Party Web sites, you should review the privacy policy posted on this other website to understand how that Third Party Web site collects and uses your Personally Identifiable Information.</p>
						<h5>Disclosure of Aggregate Information</h5>
						<p>Medvoyager may provide Aggregate Information to third parties. For example, we might inform third parties regarding the number of users of our website and the activities they conduct while on our site. We might also inform a pharmaceutical company (that may or may not be an advertiser on our site) that "30% of our users live east of the Mississippi" or that "25% of our users have tried alternative medicine." Depending on the circumstances, we may or may not charge third parties for this Aggregate Information. We require parties with whom we share Aggregate Information to agree that they will not attempt to make this information personally identifiable, such as by combining it with other databases.</p>
						<h4>How Medvoyager Handles Privacy and Security Internally</h4><br />
						<h5>Here are some of the security procedures that Medvoyager uses to protect your privacy:</h5>
						<ul class="privacyPolicy" style="font-size: 16px;">
							<li>Requires both a personal username (log-in name) and a password in order for users to access their Personally Identifiable Information or Personal Health Information.</li>
							<li>Uses firewalls to protect information held in our servers.</li>
							<li>Utilizes Secure Socket Layer (SSL) encryption in transmitting Personally Identifiable Information to our servers. In order to take advantage of encryption technology, you must have an Internet browser which supports 128-bit encryption.</li>
							<li>Closely monitors the limited number of Medvoyager employees who have potential access to your Personally Identifiable Information.</li>
							<li>Requires all Medvoyager employees to abide by our Privacy Policy and to be subject to disciplinary action if they violate it.</li>
							<li>Backs-up our systems to protect the integrity of your Personally Identifiable and Personal Health Information.</li>
						</ul>
						<br />
						<h4>Changes to This Privacy Policy</h4>
						<ul class="privacyPolicy" style="font-size: 16px;">
							<li>Personally Identifiable Information - We will inform you if a material change is made to the Privacy Policy, which means a change that expands the permissible uses or disclosures of Personally Identifiable Information allowed by the prior version of the Privacy Policy. Your continued use of the Medvoyager Web site will indicate acceptance of the changes. You may of course choose to Opt-out of continuing to use the Medvoyager Web site. Please exit the site immediately if you do not agree to the terms of this Privacy Policy or any revised policy.</li>
							<li>Personal Health Information - We will inform you if a material change in the Privacy Policy is made that involves the use of your Personal Health Information, and your express Opt-in authorization will be requested. If you choose to not accept the new privacy policy, then the current privacy policy conditions will remain in effect, so long as Medvoyager continues to make the functionality available. Medvoyager reserves the right to discontinue or limit functionality in all its products.</li>
							<li> Non-Significant Changes - Medvoyager may make non-significant changes to the Privacy Policy that does not affect Personally Identifiable Information or Personal Health Information. For these instances, Medvoyager may not notify you of such non-significant changes.</li>
							<li>If we decide to change our privacy policy, we will post those changes to this privacy statement, the home page, and other places appropriate throughout our site so that you are aware of what information we collect, how we use it, and under what circumstances, if any, we disclose it.</li>
							<li>We reserve the right to modify this privacy statement at any time, so please review it frequently. If we make material changes to this policy, we will notify you here, by email, and by means of a notice on our home page.</li>
						</ul>
						<div class="clearer"></div>
					</div>
					<div class="clearer"></div>
				</div>
			</div>
		</div>
		<div class="clearer"></div>
		<xsl:apply-templates />
	</div>
</xsl:template>

<xsl:template match="text()"/>

</xsl:stylesheet>